# Generated by Django 4.0.5 on 2022-06-29 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium_user',
            field=models.BooleanField(default=False),
        ),
    ]
