# Generated by Django 4.0.5 on 2022-06-29 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_premium_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='premium_user',
            new_name='is_premium_user',
        ),
    ]
