# Generated by Django 4.0.5 on 2022-06-15 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0003_alter_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='news_images/'),
        ),
    ]
