# Generated by Django 4.0.5 on 2022-06-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0004_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
