# Generated by Django 4.0.5 on 2022-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0005_alter_categorie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('SCRAPED', 'SCRAPED'), ('MANUAL', 'MANUAL')], default='MANUAL', max_length=20),
        ),
    ]
