# Generated by Django 4.0.5 on 2022-06-17 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0007_alter_post_image_alter_post_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user_id',
            new_name='user',
        ),
    ]
