# Generated by Django 4.0.5 on 2022-06-20 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0009_notificationtype_poststatus_notification_seen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
