# Generated by Django 4.0.5 on 2022-06-21 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0011_applicationnotification_notificationstatus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationnotification',
            name='seen',
        ),
    ]
