# Generated by Django 4.0.5 on 2022-06-22 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0012_remove_applicationnotification_seen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationnotification',
            old_name='type',
            new_name='notification_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='type',
            new_name='post_type',
        ),
        migrations.RenameField(
            model_name='postnotification',
            old_name='type',
            new_name='notification_type',
        ),
    ]
