# Generated by Django 4.0.5 on 2022-06-28 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0017_postview'),
    ]

    operations = [
        migrations.AddField(
            model_name='postview',
            name='viewed_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
