# Generated by Django 4.0.5 on 2022-06-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0018_postview_viewed_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='PCMiddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_blog.categorie')),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='news_blog.PCMiddle', to='news_blog.categorie'),
        ),
        migrations.AddField(
            model_name='pcmiddle',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_blog.post'),
        ),
    ]
