# Generated by Django 4.0.5 on 2022-06-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0019_pcmiddle_remove_post_category_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(null=True, through='news_blog.PCMiddle', to='news_blog.categorie'),
        ),
    ]
