# Generated by Django 4.0.5 on 2022-06-29 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0020_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
