# Generated by Django 4.0.5 on 2022-06-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0021_post_premium'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
