# Generated by Django 4.0.5 on 2022-06-29 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_blog', '0022_categorie_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostStatusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_on', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_blog.post')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_blog.poststatus')),
            ],
        ),
    ]
