# Generated by Django 4.0.5 on 2022-07-04 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0024_alter_post_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='news_blog.PCMiddle', to='news_blog.categorie'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpgnews_images/', upload_to='news_images/'),
        ),
    ]
