# Generated by Django 4.0.5 on 2022-07-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_blog', '0025_alter_post_category_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='news_images/default.jpg', upload_to='news_images/'),
        ),
    ]
