# MODELS VARIABLES
POST_TYPE_CHOICES = [
    ("SCRAPED", "SCRAPED"),
    ("MANUAL", "MANUAL")
]
DEFAULT_IMAGE_NAME = 'default.jpg'
POST_IMAGE_UPLOAD_TO = 'news_images/'
DEFAULT_IMAGE_PATH = DEFAULT_IMAGE_NAME+POST_IMAGE_UPLOAD_TO


# ADMIN VARIABLES
GROUP_ADMIN_NAME = 'admin'
GROUP_EDITOR_NAME = 'editor'
GROUP_MANAGER_NAME = 'manager'
GROUP_CONSUMER_NAME = 'consumer'







