# Generated by Django 4.0.5 on 2022-06-30 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
